#PBS -S /bin/bash
#PBS -q cmb
#PBS -l nodes=1:sl230s:ppn=1
#PBS -l walltime=200:00:00
#PBS -l mem=12gb
#PBS -l vmem=12gb
#PBS -l pmem=12gb
# #PBS -e qsub-logs
# #PBS -o qsub-logs

# USAGE:
#    qsub -vARGS="stuff to pass to Rscript" skeleton.pbs
# e.g.
#    qsub -vARGS="bcells-inference.R -u 02-C-M_out_of_frame -w 2 -l 2 -r 2 -k 2" skeleton.pbs

# source /usr/usc/R/3.1.0/setup.sh
source /home/rcf-40/pralph/cmb/lib/openblas-usc-R-setup.sh

cd $PBS_O_WORKDIR

echo "$ARGS"

Rscript $ARGS

exit

