---
title: "Geographic distribution of SNPs"
date: "`r date()`"
---


```{r setup, include=FALSE}
library(pander)
options(scipen=3)
fig.dim <- 5
knitr::opts_chunk$set(fig.height=fig.dim,fig.width=2*fig.dim,fig.align='center')
### set-up as in explore-mitochondria.Rmd
# locations and labels
coord.obj <- load(file.path("../tort_272_info","geog_coords.RData"))
coords <- get(coord.obj)
tort.ids <- row.names(coords)
```

First, let's pull out some random alleles
(and cache these, since it takes a while).
So that we have plenty, let's say 100 alleles
for each decile of frequency:
```{r get_counts, cache=TRUE}
info.header <- scan("../../angsd-counts/272torts_snp1e6_minmapq20minq30.mafs.gz",nlines=1,what="char")
count.header <- scan("../../angsd-counts/272torts_snp1e6_minmapq20minq30.counts.gz",nlines=1,what="char")
count.list <- parallel::mclapply( ((0:5)*10)/100, function (pmin) {
        read.table( pipe( 
                 paste("bash -c '../count-utils/get-random-site.sh",
                      "<(zcat ../../angsd-counts/272torts_snp1e6_minmapq20minq30.mafs.gz | head -n 100001 | gzip -c)",
                      "<(zcat ../../angsd-counts/272torts_snp1e6_minmapq20minq30.counts.gz | head -n 100000 | gzip -c)",
                      pmin, pmin+0.1, 100, "'") 
                 ), header=TRUE )
    }, mc.cores=8 )
info.list <- lapply( count.list, function (x) { x <- x[,1:length(info.header)]; names(x) <- info.header; x } )
count.list <- lapply( count.list, function (x) { x <- x[,length(info.header)+seq_along(count.header)]; colnames(x) <- count.header; as.matrix(x) } )
```

```{r read_data}
## read in data
bases <- c("A","C","G","T")
base.cols <- adjustcolor(1:4,.5)
nsamples <- length(count.header)/4
stopifnot( length(tort.ids) == nsamples )
indivs <- tort.ids
eval.counts <- function (counts,expr) {
    ## evaluate expr after setting some things up from counts
    # counts by base
    clist <- lapply(c(A=1,C=2,G=3,T=4),function(shift){counts[,shift+seq(0,by=4,length.out=nsamples)]})
    colnames(clist$A) <- colnames(clist$C) <- colnames(clist$G) <- colnames(clist$T) <- indivs
    # coverage by tort and site
    coverage <- clist$A + clist$C + clist$G + clist$T
    # total coverage by site and allele
    total <- do.call(cbind,lapply(clist,rowSums))
    # total coverage by site
    total.coverage <- rowSums(coverage)
    # major allele overall
    major.allele <- apply(total,1,which.max)
    eval( substitute(expr) )
}
# use this like:
#  sapply( count.list, eval.counts, {mean(coverage)} )
```

```{r raster_setup, include=FALSE}
library(raster)
library(maptools)
layer <- raster("../visualization/dem_30")
player <- function (main='') { plot(layer,legend=FALSE,xlab="",ylab="",xaxt="n",yaxt="n",legend.mar=0,box=FALSE,main=main) }
# read in other info
pcs <- read.csv(file.path("../tort_272_info","pcs.csv"),header=TRUE,stringsAsFactors=FALSE)
stopifnot( all( tort.ids %in% pcs$etort ) )
pc.cols <- adjustcolor( ifelse( pcs$PC1[match(tort.ids,pcs$etort)] > 0, "blue", "purple" ), .75 )
```

Geographic distribution of segregating sites
============================================

Here are maps of 18 alleles in the first frequency group:
```{r map_alleles, fig.width=3*fig.dim}
layout(t(1:3))
for (counts in count.list) {
    eval.counts( counts, { for (n in 1:24) { player(); for (k in 1:4) { points(coords,pch=20,cex=clist[[k]][n,],col=base.cols[k]) } } } )
}
```

