options(error=recover)
source(list.files()[grepl("space.mix.MCMC",list.files())])
load(list.files()[grepl("dataset",list.files())])

run.spacemix.analysis(	n.fast.reps = 0,
						fast.MCMC.ngen = 1e3,
						fast.model.option = "target",
						long.model.option = "target",
						data.type = "sample.covariance",
						fast.likelihood.option = NULL,
						long.likelihood.option = "wishart",
						proj.mat.option=NULL,
						sample.frequencies=NULL,
						mean.sample.sizes=mean.sample.sizes,
						counts = NULL,
						sample.sizes = NULL,
						sample.covariance=sample.covariance,
						target.spatial.prior.scale=NULL,
						source.spatial.prior.scale=NULL,
						spatial.prior.X.coordinates = tort.coords[,1],
						spatial.prior.Y.coordinates = tort.coords[,2],
						round.earth = TRUE,
						long.run.initial.parameters=NULL,
						k = nrow(tort.coords),
						loci = 1e5,
						ngen = 1e7,
						printfreq = 1e3,
						samplefreq = 1e4,
						mixing.diagn.freq = 50,
						gibbs.nugget.fineness=50,
						gibbs.spatial.fineness=50,
						gibbs.step.frequency=1e10,
						savefreq=1e5,
						directory=NULL,
						prefix="tort_locations")