```{r setup, include=FALSE}
source("../resistance-fns.R")
require(parallel); numcores=getcores()
require(xtable)
fig.dim <- 5
opts_chunk$set(fig.height=fig.dim,fig.width=2*fig.dim,fig.align='center')
subdirs <- list.dirs(".",recursive=FALSE,full.names=FALSE)
has.results <- sapply( subdirs, function (subdir) { length(list.files(subdir,pattern="inference-.*RData",full.names=TRUE)) } )
get.results <- function (subdir,numcores=1) {
    result.files <- list.files(subdir,pattern="inference-.*RData",full.names=TRUE)
    if ( (!file.exists(file.path(subdir,"config.json"))) | (length(result.files)==0) ) { return( list( subdir=subdir ) ) }
    config <- read.json.config(file.path(subdir,"config.json"))
    for (x in file.path(subdir,config$setup_files)) { load(x) }
    last.result <- result.files[ rev(order( file.info(result.files)$mtime )) ][1]
    load(last.result)
    params <- trust.optim$argument
    environment(update.G) <- environment(valfn) <- environment(transfn) <- environment()
    G@x <- update.G(params[-1])
    gamma <- params[2+(1:length(layer.names))]
    stationary.base <- rowSums( layers * gamma[col(layers)] )
    jump.rates <- rowSums(G)
    hts <- tryCatch( { hitting.analytic(neighborhoods,G,numcores=numcores)[locs,] },
        error=function (cond) {message(cond);message(paste("Error in",subdir)); NA}, 
        warning=function (cond) {message(cond);message(paste("Warning in",subdir)); NA} )
    return( list( subdir=subdir, params=params, hts=hts, pimat=pimat, layer.names=layer.names, value=trust.optim$value, 
            converged=trust.optim$converged, accept.rate=mean(trust.optim$accept), 
                stationary.base=stationary.base, jump.rates=jump.rates,
                trust.optim=trust.optim, iterations=trust.optim$iterations ) )
}
run.info.files <- list.files(".","run-info.*RData")
if (length(run.info.files)>0) {
    run.info.file <- run.info.files[ rev(order(file.info(run.info.files)$mtime)) ][1]
    cat("Loading from: ", run.info.file)
    load(run.info.file)
} else {
    run.info <- mclapply( subdirs, get.results, mc.cores=numcores )
    run.info.file <- paste("run-info-",format(Sys.time(),"%d-%m-%Y-%H_%M_%S"),".RData",sep='')
    cat("Saving to: ", run.info.file)
    save(run.info,file=run.info.file)
}
all.layer.names <- c("constant", unique( unlist( lapply( run.info, "[[", "layer.names" ) ) ) )
run.gamma <- matrix( NA, nrow=length(run.info), ncol=length(all.layer.names) )
run.delta <- matrix( NA, nrow=length(run.info), ncol=length(all.layer.names) )
colnames(run.gamma) <- colnames(run.delta) <- all.layer.names
denull <- function (x) { x[sapply(x,is.null)] <- NA; unlist(x) }
run.params <- data.frame( 
        value=denull(lapply( run.info,"[[","value" )),
        T=denull(lapply( lapply(run.info,"[[","params"), "[", 1 )), 
        beta=denull(lapply( lapply(run.info,"[[","params"), "[", 2 )),
        converged=denull(lapply( run.info,"[[","converged" )),
        iterations=denull(lapply( lapply( run.info,"[[","trust.optim"), "[[", "iterations" )),
        accept.rate=denull(lapply( run.info,"[[","accept.rate" ))
    )
for (k in seq_along(run.info)) {
    these.layer.names <- run.info[[k]]$layer.names
    these.layers <- run.info[[k]]$layer.names
    run.gamma[k,match(these.layers,all.layer.names)] <- run.info[[k]]$params[2+(1:length(these.layers))]
    run.delta[k,match(these.layers,all.layer.names)] <- run.info[[k]]$params[2+length(these.layers)+(1:length(these.layers))]
}
value.order <- order(run.params$value)
```

Here is a table of the results:
```{r results_tab, results="asis"}
ptab <- xtable( run.params[value.order,], digits=c(0,0,0,2,0,0,2) )
print(ptab,type='html')
```
and the gamma parameters:
```{r results_gamma, results="asis"}
gtab <- xtable( run.gamma[value.order,] )
print(gtab,type='html')
```
and the delta parameters:
```{r results_delta, results="asis"}
dtab <- xtable( run.delta[value.order,] )
print(dtab,type='html')
```

Here's the observed hitting times against geographic distance (with the self-comparisons removed):
```{r geog_dist,fig.width=fig.dim}
if (file.exists("../torts-info.RData")) {
    load("../torts-info.RData")  # for distances, tort.dists
    pimat <- run.info[[value.order[1]]]$pimat
    diag(pimat) <- NA
    ref.inds <- run.info[[value.order[1]]]$trust.optim$ref.inds
    used <- (col(pimat)%in%ref.inds) & (row(pimat)%in%ref.inds)
    plot( as.vector(tort.dists), pimat, col=adjustcolor(ifelse(col(pimat)%in%ref.inds,'red','black'),0.25), pch=20, cex=0.5, ylab="observed times", xlab="geographic distance" )
}
```

Now, plots of inferred hitting times against the observed
(zoomed in on the right):
```{r plot_hts, fig.width=3*fig.dim, echo=FALSE}
for ( k in value.order ) {
    if (length(run.info[[k]])>1) {
        # set up plotting
        tmp.config <- read.json.config(file.path("..",run.info[[k]]$trust.optim$config.file))
        load(file.path(run.info[[k]]$subdir,tmp.config$setup_files))
        tort.loc.obj <- load(file.path(run.info[[k]]$subdir,tmp.config$sample_locs))
        assign("tort.locs",get(tort.loc.obj)[!na.indiv])
        ph <- plot.ht.fn("../../geolayers/multigrid/256x/crm_",nonmissing,homedir="../..",default.par.args=list(mar=c(3,3,3,3)+.1))
        # and hitting times
        sym.hts <- run.params$T[k] + run.info[[k]]$hts
        sym.hts <- (sym.hts+t(sym.hts))/2
        diag(sym.hts) <- NA
        pimat <- run.info[[k]]$pimat
        diag(pimat) <- NA
        mean.resids <- rowMeans( sym.hts - pimat, na.rm=TRUE )
        ref.inds <- run.info[[k]]$trust.optim$ref.inds
        used <- (col(pimat)%in%ref.inds) & (row(pimat)%in%ref.inds)
        subdir <- run.info[[k]]$subdir
        xlims <- range(sym.hts[used],na.rm=TRUE)
        ylims <- range(pimat[used],na.rm=TRUE)
        # plot
        layout(matrix(1:4,nrow=2,byrow=TRUE))
        plot( as.vector(sym.hts), pimat, col=adjustcolor(ifelse(used,'red','black'),0.25), pch=20, cex=0.5, ylab="observed times", xlab="fitted times" )
        legend("bottomright",pch=20,col=c("red","black"),legend=c("used in fitting","not used in fitting"))
        abline(0,1)
        plot( as.vector(sym.hts), pimat, col=adjustcolor(ifelse(used,'red','black'),0.25), 
            pch=20, cex=0.5, ylab="observed times", xlab="fitted times", 
            xlim=xlims, ylim=ylims )
        legend("bottomright",pch=20,col=c("red","black"),legend=c("used in fitting","not used in fitting"))
        abline(0,1)
        ph( pmin(1e3,run.info[[k]]$jump.rates), main=subdir, do.lims=FALSE, zlims=c(0,1e3) )
        points(tort.locs); points(tort.locs,cex=abs(scale(mean.resids)),col=ifelse(mean.resids>0,"red","blue"))
        z <- 1/(1+exp(-run.info[[k]]$stationary.base))
        ph( z/sum(z), do.lims=FALSE )
        points(tort.locs); points(tort.locs,cex=abs(scale(mean.resids)),col=ifelse(mean.resids>0,"red","blue"))
    }
}
```
